### PR TITLE
Fix/chart resize when updating props

### LINKED ISSUE #49: 🐛 [BUG] - @eazychart - [react] - Chart is resizing when updating props
### Description

The chart component is resizing whenever its props are updated. I made some investigation about this bug, and I found out that the `legendHeight` located in the `packages/ez-react/src/components/Chart.tsx` is 0 when the component gets mounted. 

I also found out that the ref forwarded from the `Legend` component is not updated in the `Chart` component.  To explain it further, when `console.log`-ing into the Legend component, you can find the ref, having a value (in this case the ref of the `div` wrapping the legends). But when you are `console.log`-ing the ref of the `Legend` component which is supposed to be the same as the `ref` into the `Legend` component from the parent which is chart, the ref has a value of `null`. `legendRef.current` will only have a value of the Legend div when it gets updated. 

### Reproduction steps
1. Run storybook :
```bash
yarn storybook:react
```
2. Select any chart.
3. Toggle any legend item.
4. The chart will shrink.

### PR DESCRIPTION
**Pull request by IlyesBenAmara**
# Motivation

Fixed the chart resize problem that occurs when the chart props are updated. 

Fixes #49 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have done the work for both react and vue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ez-react/src/components/addons/legend/Legend.tsx [hunk 1]
```diff
@@ -31,18 +32,45 @@ export const Legend: React.FC<LegendPropsWithRef> = React.forwardRef<
     }
   }, [colorScale]);
 
+  const resizeChart: Function = (entries: ResizeObserverEntry[]) => {
```
Comment (marrouchi) [inline packages/ez-react/src/components/addons/legend/Legend.tsx:35]:
```suggestion
  const handleResize: Function = (entries: ResizeObserverEntry[]) => {
```

File: packages/ez-react/src/components/addons/legend/Legend.tsx [hunk 2]
```diff
@@ -31,18 +32,45 @@ export const Legend: React.FC<LegendPropsWithRef> = React.forwardRef<
...
-          <LegendItem
-            key={key}
-            onToggle={onLegendClick}
-            label={key}
-            color={color}
-          />
-        );
-      })}
-    </div>
+    ref && (
```
Comment (marrouchi) [inline packages/ez-react/src/components/addons/legend/Legend.tsx:61]:
```suggestion
    (
```

**Review by marrouchi — CHANGES_REQUESTED** [review]
:guitar:

**Review by marrouchi — APPROVED** [review]
:rocket:
